name: "setup-java"
description: "Set up Java"
inputs:
  java-version:
    description: "java-version"
    default: 11
    required: false

  distribution:
    description: "distribution"
    default: adopt
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
