# Cancel workflow runs associated with a pull request when it is closed or merged.
name: Cancel

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: read

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: write # to cancel workflow runs
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require(
              `${process.env.GITHUB_WORKSPACE}/.github/workflows/cancel.js`
            );
            await script({ context, github });
