name: Closing PR

on:
  pull_request_target:
    types:
      - opened
      - edited

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

permissions:
  contents: read

jobs:
  closing-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: read # closing-pr.js reads the PR body
      issues: write # closing-pr.js labels issues
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7.0.0
        with:
          script: |
            const script = require(
              `${process.env.GITHUB_WORKSPACE}/.github/workflows/closing-pr.js`
            );
            script({ context, github });
