name: Devcontainer

on:
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - .devcontainer/**

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.repository == 'mlflow/mlflow'
    permissions:
      packages: write # to push to ghcr.io
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Get image name
        run: |
          IMAGE_NAME=$(yq '.services.mlflow.image' .devcontainer/docker-compose.yml)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
      - name: Build image
        run: |
          docker build -f .devcontainer/Dockerfile.devcontainer -t $IMAGE_NAME .
      - name: Show layer sizes
        run: |
          docker history $IMAGE_NAME
      - name: Inspect image
        run: |
          docker image inspect $IMAGE_NAME
      - name: Test Image
        run: |
          docker run --rm -v $(pwd):/workspaces/mlflow $IMAGE_NAME bash -c "pip install --no-deps -e . && pytest tests/test_version.py"
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        if: github.event_name == 'push'
        run: |
          docker push $IMAGE_NAME
