name: Labeling

on:
  issues:
    types:
      - opened
      - edited
  pull_request_target:
    types:
      - opened
      - edited

permissions:
  contents: read

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  labeling:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # harupy/auto-labeling
      issues: write # harupy/auto-labeling
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
      - uses: harupy/auto-labeling@937d558e37285af6ca5c5813a826cf6f0d66bf0f # master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-pattern: '- \[(.*?)\] ?`(.+?)`'
