# Cross version tests sometimes fail due to transient errors. This workflow reruns failed tests.
name: rerun-cross-version-tests

on:
  schedule:
    # Run this workflow daily at 17:00 UTC (4 hours after cross-version-tests.yml workflow)
    - cron: "0 17 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.repository == 'mlflow-automation/mlflow'
    permissions:
      actions: write # to rerun workflows
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const rerun = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/rerun.js`);
            await rerun({ context, github, workflow_id: "cross-version-tests.yml" });
